import type { RoutineTemplateLibraryEntry } from "@/lib/routine-template-library";

const AUTOMOTIVE = ["automotive"] as const;
const LAKK = ["automotive", "skade_lakk"] as const;
const PKK = ["automotive", "pkk"] as const;

function createContent(params: RoutineTemplateLibraryEntry["content"]): RoutineTemplateLibraryEntry["content"] {
  return params;
}

function automotiveRoutine(params: {
  title: string;
  description: string;
  category: string;
  legalReference: string;
  industryScope: readonly string[];
  content: RoutineTemplateLibraryEntry["content"];
}): RoutineTemplateLibraryEntry {
  return {
    title: params.title,
    description: params.description,
    category: params.category,
    legalReference: params.legalReference,
    industryScope: [...params.industryScope],
    reviewIntervalMonths: 12,
    content: createContent(params.content),
  };
}

const kjerne: RoutineTemplateLibraryEntry[] = [
  automotiveRoutine({
    title: "Arbeid på kjøretøyløfter, løftebukk og under bil",
    description: "Når: før jobb. Dokumentert og utstyrsspesifikk opplæring før bruk av billøfter. FuA kap. 10 og 12.",
    category: "BILVERKSTED",
    legalReference: "FuA §§ 10-2, 10-4 og kap. 12",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Sikre at kjøretøy løftes og sikres slik at ingen klemmes eller treffes av fallende last.",
      omfang: "Alle som bruker kjøretøyløfter, sakseløfter, grav eller løftebukk i hallen.",
      ansvar: [
        "Teknisk leder: sørger for opplæring, vedlikehold og at kun opplærte bruker løfteren.",
        "Mekaniker: daglig kontroll og riktig oppstilling før arbeid under bil.",
        "Verneombud: varsler ved skade eller manglende kontroll.",
      ],
      gjennomforing: [
        "Kun personell med dokumentert opplæring (FuA § 10-2) og utstyrsspesifikk opplæring på den enkelte løfteren (FuA § 10-4) skal bruke utstyret.",
        "Utfør daglig kontroll etter sjekkliste før første løft. Stans ved feil – opprett avvik.",
        "Plasser armer og gummiklosser etter produsent og kjøretøyets løftepunkter. Ingen under bil før den er sikret.",
        "Hold sperreområde fritt. Kommuniser før senking. Krysslenke: SJA «Løft og arbeid under kjøretøy».",
      ],
      dokumentasjon: ["Opplæringsbevis per løfter i kompetansemodulen.", "Daglig kontroll og vedlikehold/kalibrering."],
      avvikOppfolging: ["Skade, nestenulykke eller utløpt kontroll meldes som avvik. Utløpt kalibrering er avvik, ikke et eget system."],
      revisjon: "Revideres årlig eller ved ny løfter / alvorlig hendelse.",
      kilder: ["FuA §§ 10-2 og 10-4 – opplæring i arbeidsutstyr", "FuA kap. 12 – kontroll og vedlikehold", "AML § 3-2"],
    },
  }),
  automotiveRoutine({
    title: "Arbeid i arbeidsgrav",
    description: "Når: før jobb. Fall, eksos og orden ved arbeid i grav.",
    category: "BILVERKSTED",
    legalReference: "Arbeidsplassforskriften §§ 7-1–7-3, AML § 4-1",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Forebygge fall i grav og forgiftning fra eksos når motor går.",
      omfang: "Verksteder med arbeidsgrav eller inspeksjonsgrop.",
      ansvar: ["Teknisk leder: sikring, belysning og avsug.", "Mekaniker: ikke tomgang uten avsug. Overdekk grav når den ikke er i bruk."],
      gjennomforing: [
        "Grav skal ha rekkverk, overdekking eller tilsvarende sikring når den ikke er i bruk.",
        "Motor i gang kun med eksosavsug tilkoblet. Ingen tomgang for oppvarming i grav.",
        "God belysning og tørt, ryddig gulv. Krysslenke: sjekkliste vernerunde hall.",
      ],
      dokumentasjon: ["Vernerundefunn.", "Vedlikehold av avsug."],
      avvikOppfolging: ["Manglende sikring eller avsug meldes som avvik umiddelbart."],
      revisjon: "Årlig, og etter fallhendelse.",
      kilder: ["Arbeidsplassforskriften §§ 7-1–7-3", "AML § 4-1"],
    },
  }),
  automotiveRoutine({
    title: "Eksosavsug og dieseleksos – motor inne",
    description: "Når: i jobb. Grenseverdi 0,05 mg/m³ EC. Arbeidsplassforskriften § 7-1.",
    category: "BILVERKSTED",
    legalReference: "Arbeidsplassforskriften § 7-1, forskrift om tiltaks- og grenseverdier",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Hindre at ansatte puster inn dieseleksos over grenseverdien og dokumentere eksponering.",
      omfang: "All kjøring og diagnosetest med motor i gang innendørs.",
      ansvar: [
        "Arbeidsgiver: avsug, måling og eksponeringsregister (FuA kap. 31, 60 år).",
        "Mekaniker: koble avsug før motor startes inne.",
      ],
      gjennomforing: [
        "Koble punktavsug på eksosrør før motor startes i hall. Unngå tomgang uten behov.",
        "Dieseleksos har grenseverdi 0,05 mg/m³ EC og anmerkning K/G fra 21.02.2023. Kartlegg og mål ved tvil.",
        "Registrer eksponerte i eksponeringsregisteret. Krysslenke: stoffkartotek og sjekkliste avsug.",
      ],
      dokumentasjon: ["Eksponeringsregister 60 år.", "Målerapporter.", "Vedlikehold av avsug."],
      avvikOppfolging: ["Manglende avsug eller synlig røyk i hall er avvik. Stans motor inne til avsug virker."],
      revisjon: "Årlig eller ved endret hall/ventilasjon.",
      kilder: ["Arbeidsplassforskriften §§ 7-1–7-3", "Forskrift om tiltaks- og grenseverdier – dieseleksos 0,05 mg/m³ EC", "FuA kap. 31"],
    },
  }),
  automotiveRoutine({
    title: "Kjemikalier, stoffkartotek, substitusjon og mineralolje på hud",
    description: "Når: i jobb. AML § 4-5 og FuA kap. 3. Åpner stoffkartoteket.",
    category: "KJEMIKALIER",
    legalReference: "AML § 4-5, FuA kap. 3",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Sikre at farlige kjemikalier er kjent, substituert der det er mulig, og at hud ikke smøres inn med mineralolje.",
      omfang: "Olje, bremsevæske, løsemidler, lim, lakk og rengjøringsmidler i verkstedet.",
      ansvar: ["HMS-ansvarlig: stoffkartotek og SDS.", "Mekaniker: les SDS, bruk hansker, ikke vask hender i white-spirit."],
      gjennomforing: [
        "Alle farlige kjemikalier skal ligge i stoffkartoteket med oppdatert SDS. Åpne stoffkartoteket fra denne rutinen.",
        "Vurder substitusjon av de farligste stoffene (Miljøfyrtårn-kriterium).",
        "Mineralolje på hud er kreftfare – hansker og hudpleie. Registrer i eksponeringsregister 60 år.",
      ],
      dokumentasjon: ["Stoffkartotek.", "Eksponeringsregister.", "Substitusjonsvurdering."],
      avvikOppfolging: ["Manglende SDS eller åpen beholder uten merking er avvik."],
      revisjon: "Årlig og ved nye produkter.",
      kilder: ["AML § 4-5", "FuA kap. 3", "FuA kap. 31"],
    },
  }),
  automotiveRoutine({
    title: "Sveising og varmt arbeid – sveiserøyk i eksponeringsregister",
    description: "Når: før jobb. FuA kap. 5 og 31. SJA før sveising.",
    category: "BILVERKSTED",
    legalReference: "FuA kap. 5 og kap. 31",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Forebygge brann og kreftfare fra sveiserøyk, og dokumentere hvem som sveiser.",
      omfang: "Sveising, skjæring og annet varmt arbeid i hall eller på kjøretøy.",
      ansvar: ["Teknisk leder: avsug, varmt arbeid-kompetanse.", "Sveiser: SJA, avsug og verneutstyr før start."],
      gjennomforing: [
        "SJA «Sveising i hall» før start. Gyldig varmt arbeid-sertifikat.",
        "Punktavsug og åndedrettsvern. Sveiserøyk er IARC-kreftfremkallende – informasjonsblad til ansatte.",
        "Fjern brennbart, ha slokkeutstyr og brannvakt. Registrer sveisere i eksponeringsregister 60 år.",
      ],
      dokumentasjon: ["SJA.", "Eksponeringsregister.", "Varmt arbeid-bevis."],
      avvikOppfolging: ["Sveising uten avsug eller uten SJA er avvik."],
      revisjon: "Årlig.",
      kilder: ["FuA kap. 5 – kjemikalier ved varmt arbeid", "FuA kap. 31 – eksponeringsregister", "Forskrift om brannforebygging"],
    },
  }),
  automotiveRoutine({
    title: "Farlig avfall, oljeutskiller, batteri- og dekkretur",
    description: "Når: uke. Avfallsforskriften kap. 11, 3 og 5. Fase 1 uten leveringslogg.",
    category: "MILJO",
    legalReference: "Avfallsforskriften kap. 11, 3 og 5",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Håndtere spillolje, filtre, batteri, dekk og kjemikalieavfall uten utslipp eller feilsortering.",
      omfang: "Alt farlig avfall fra verkstedet, inkludert lakkslam der det er aktuelt.",
      ansvar: ["Daglig leder: avtale med godkjent mottak.", "HMS-ansvarlig: merking og oljeutskiller."],
      gjennomforing: [
        "Sorter spillolje, oljefiltre, bremsevæske, frostvæske, spraybokser, absorbenter og batteri i merkede beholdere.",
        "Dekk og batteri har returplikt (avfallsforskriften kap. 3 og 5). Lever til godkjent mottak.",
        "Oljeutskiller skal virke. Sjekk ved vernerunde. Kvittering arkiveres i dokumenter (leveringslogg er fase 2).",
      ],
      dokumentasjon: ["Mottakskvitteringer.", "Vernerunde oljeutskiller."],
      avvikOppfolging: ["Utslipp til sluk eller feilavfall er miljøavvik."],
      revisjon: "Årlig.",
      kilder: ["Avfallsforskriften kap. 11 – farlig avfall", "Avfallsforskriften kap. 3 og 5 – batteri og dekk"],
    },
  }),
  automotiveRoutine({
    title: "El- og hybridbil – høyvolt etter NBF-praksis",
    description: "Når: før jobb. To-mannsregel, isolert verktøy, frakobling etter produsent. AML § 3-2, verkstedforskriften § 11.",
    category: "BILVERKSTED",
    legalReference: "AML § 3-2, verkstedforskriften § 11",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Hindre strømskade ved arbeid på drivbatteri og oransje høyspenningskabler.",
      omfang: "Alle el- og hybridbiler. SJA er påkrevd ved arbeid på høyspenning.",
      ansvar: ["Teknisk leder: kompetanse og merking av sone.", "Faglært: utfører frakobling. Lærling kun under tilsyn."],
      gjennomforing: [
        "Bruk SJA «Høyvolt / frakobling drivbatteri» og sjekkliste for spenningsfrihet før arbeid på HV-system.",
        "NBF: to-mannsregel, isolert verktøy, frakobling etter produsentanvisning, merking og avsperring.",
        "Årlig repetisjon av elbil-opplæring. Førstehjelp strømskade skal være kjent.",
      ],
      dokumentasjon: ["SJA.", "Kompetansebevis.", "Utført sjekkliste spenningsfrihet."],
      avvikOppfolging: ["Arbeid på HV uten frakobling eller uten opplæring er stans og avvik."],
      revisjon: "Årlig eller ved ny merke/modell med andre prosedyrer.",
      kilder: ["Verkstedforskriften § 11 – kompetanse", "AML § 3-2", "NBF: Sikkert arbeid rundt høyenergibatterier"],
    },
  }),
  automotiveRoutine({
    title: "Karantene og brann i litiumbatteri / thermal runaway",
    description: "Når: i jobb. DSB og NBF-veileder for skadet eller ladende drivbatteri.",
    category: "BILVERKSTED",
    legalReference: "DSB farlig stoff, NBF-veileder",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Begrense skade ved termisk løpsk i litiumbatteri.",
      omfang: "Skadede, defekte eller under lading stående drivbatterier og elbil i hall.",
      ansvar: ["Teknisk leder: karanteneområde og brannplan.", "Alle: evakuer ved røyk fra batteri."],
      gjennomforing: [
        "Skadet batteri lagres i avtalt karantene, ikke i vanlig lager. Følg NBF/DSB for slokking og avstand.",
        "Lading av uttatte batterier kun der det er avtalt og med tilsyn.",
        "Ved røyk eller varme: evakuer, varsle brannvesen, ikke åpne batteriet.",
      ],
      dokumentasjon: ["Karanteneplass i håndbok/plantegning.", "Brannøvelse som inkluderer batteribrann."],
      avvikOppfolging: ["Lagring av skadet batteri uten plan er avvik."],
      revisjon: "Årlig.",
      kilder: ["DSB – litiumbatterier", "NBF-veileder høyenergibatterier"],
    },
  }),
  automotiveRoutine({
    title: "Prøvekjøring og flytting av kundebil",
    description: "Når: før jobb. Sjekk før vei. Trafikksikkerhet og kundebil.",
    category: "BILVERKSTED",
    legalReference: "Vegtrafikkloven, AML § 4-1",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Unngå ulykke og skade på kundebil ved prøvekjøring og intern flytting.",
      omfang: "All kjøring av kundebil på vei og i anlegg.",
      ansvar: ["Teknisk leder: hvem som har førerrett.", "Sjåfør: sjekkliste før vei."],
      gjennomforing: [
        "Kun ansatte med gyldig førerrett for klassen. Førerkort registreres i kompetanse.",
        "Sjekkliste «Før prøvekjøring»: bremser, hjul, lys, væsker, last. SJA ved krevende test.",
        "Kortest mulig rute. Personvern: ikke bruk kundens infotainment privat.",
      ],
      dokumentasjon: ["Sjekkliste.", "Førerrett i kompetansemodulen."],
      avvikOppfolging: ["Ulykke, skade på kundebil eller kjøring uten sjekk er avvik/kundeklage."],
      revisjon: "Årlig.",
      kilder: ["Vegtrafikkloven", "AML § 4-1"],
    },
  }),
  automotiveRoutine({
    title: "Dekk- og hjularbeid",
    description: "Når: i jobb. Klemfare, sprengning og moment.",
    category: "BILVERKSTED",
    legalReference: "FuA kap. 10 og 12, AML § 4-4",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Forebygge klemskade, sprengning og hjul som løsner etter montasje.",
      omfang: "Hjulskift, dekkhotell og dekkmaskin.",
      ansvar: ["Teknisk leder: opplæring på dekkmaskin.", "Mekaniker: moment etter produsent."],
      gjennomforing: [
        "Bruk løftehjelp ved tunge hjul. SJA «Hjulavtrekk / dekkmontering» ved dekkmaskin.",
        "Aldri overtrykk. Bruk bur/skjerm der det kreves. Rett moment og ettertrekk.",
        "Merk sesongdekk og kundeeie. Personvern for registreringsnummer i dekkhotell.",
      ],
      dokumentasjon: ["Opplæring dekkmaskin.", "Momentverdier etter produsent."],
      avvikOppfolging: ["Hjul som løsner eller sprengning er alvorlig avvik."],
      revisjon: "Årlig.",
      kilder: ["FuA kap. 10 og 12", "AML § 4-4"],
    },
  }),
  automotiveRoutine({
    title: "Airbag og pyroteknikk",
    description: "Når: i jobb. Håndtering av usprengt airbag og beltestrammere.",
    category: "BILVERKSTED",
    legalReference: "AML § 4-1, produsentanvisning",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Unngå utilsiktet utløsning av pyroteknikk og skade på øyne/hørsel.",
      omfang: "Demontering, lagring og arbeid nær airbag og beltestrammere.",
      ansvar: ["Teknisk leder: lagring og opplæring.", "Mekaniker: produsentens deaktiveringsprosedyre."],
      gjennomforing: [
        "Følg produsentanvisning. Frakoble batteri og vent anbefalt tid før arbeid i dash/ratt.",
        "Usprengte enheter lagres merket, tørt og uten varme. Ikke kast i vanlig avfall.",
        "Vernebriller ved demontering. Lærling kun under tilsyn.",
      ],
      dokumentasjon: ["Produsentanvisning.", "Avfallslevering av pyroteknikk."],
      avvikOppfolging: ["Utilsiktet utløsning er hendelse med RUH."],
      revisjon: "Årlig.",
      kilder: ["AML § 4-1", "Produsentanvisning SRS"],
    },
  }),
  automotiveRoutine({
    title: "Mistanke om asbest i bremse- og clutchbelegg",
    description: "Når: i jobb. FuA kap. 4: stans, ikke tørrblåsing. Verkstedet skal unngå, ikke sanere.",
    category: "BILVERKSTED",
    legalReference: "FuA kap. 4",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Hindre asbesteksponering fra eldre bremse- og clutchbelegg.",
      omfang: "Eldre kjøretøy der originalbelegg kan inneholde asbest.",
      ansvar: ["Teknisk leder: stans og videre håndtering.", "Mekaniker: ikke blås med trykkluft."],
      gjennomforing: [
        "Ved mistanke: stans arbeidet. Ikke tørrblåsing, sliping eller feiing av støv.",
        "Fukt og pakk avfall. Asbestsanering krever godkjent virksomhet – verkstedet søker ikke selv.",
        "Informer ansatte. Vurder eksponeringsregister hvis arbeid likevel er utført.",
      ],
      dokumentasjon: ["Hendelseslogg.", "Eventuell overlevering til godkjent sanering."],
      avvikOppfolging: ["Arbeid med mistenkt asbest uten tiltak er alvorlig avvik."],
      revisjon: "Årlig.",
      kilder: ["FuA kap. 4 – asbest"],
    },
  }),
  automotiveRoutine({
    title: "Støy og vibrasjon – hørselsvern og BHT-helseundersøkelse",
    description: "Når: år. FuA kap. 14. Tiltaksverdi 85 dB. BHT-plikt NACE 45.2.",
    category: "BILVERKSTED",
    legalReference: "FuA kap. 14, BHT-forskriften NACE 45.2",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Forebygge hørselsskade og HAV-skade, og utløse BHT-undersøkelse ved behov.",
      omfang: "Slagverktøy, sliping, dekkmaskin og kompressor.",
      ansvar: ["Arbeidsgiver: kartlegging og BHT-avtale.", "Ansatt: bruk hørselsvern der det er påbudt."],
      gjennomforing: [
        "Kartlegg støy og vibrasjon med sjekkliste. Ved tvil: måling. Tiltaksverdi 85 dB.",
        "Hørselsvern og jobbrotasjon. Lavvibrasjonsverktøy der det finnes.",
        "BHT-helseundersøkelse når tiltaksverdier overskrides. Bilverksted er BHT-pliktig (NACE 45.2 / 45.403).",
      ],
      dokumentasjon: ["Kartlegging.", "BHT-rapport.", "Utstyrt hørselsvern."],
      avvikOppfolging: ["Manglende hørselsvern i merket sone er avvik."],
      revisjon: "Årlig.",
      kilder: ["FuA kap. 14", "Forskrift om org. ledelse og medvirkning vedlegg 1 – BHT"],
    },
  }),
  automotiveRoutine({
    title: "Lærling og unge under 18",
    description: "Når: i jobb. OLM kap. 12: tilsyn og forbud mot visse kjemikalier og høyvolt alene.",
    category: "BILVERKSTED",
    legalReference: "OLM kap. 12 og § 8-1",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Sikre at unge arbeidstakere ikke settes til forbudt eller usikret farlig arbeid.",
      omfang: "Lærlinger og ansatte under 18 år.",
      ansvar: ["Faglig leder/veileder: tilsyn.", "Teknisk leder: forbudsliste kjent i hallen."],
      gjennomforing: [
        "Unge skal ha tilsyn. De skal ikke arbeide alene med høyvolt, asbestmistanke, diisocyanater eller farlige maskiner uten opplæring.",
        "Opplæring før selvstendig arbeid (AML § 3-2). SJA gjennomgås med veileder.",
        "Arbeidstid for unge følger OLM. Nattarbeid er begrenset.",
      ],
      dokumentasjon: ["Opplæringsplan.", "Tilsyn/veiledning."],
      avvikOppfolging: ["Unge alene på forbudt arbeid er alvorlig avvik."],
      revisjon: "Årlig og ved ny lærling.",
      kilder: ["OLM kap. 12", "OLM § 8-1", "AML § 3-2"],
    },
  }),
  automotiveRoutine({
    title: "F-gass / AC-service kun med gyldig bevis",
    description: "Når: før jobb. Produktforskriften. Sertifisering hos Isovator/Incert – vi registrerer gyldighet.",
    category: "BILVERKSTED",
    legalReference: "Produktforskriften – F-gass",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Sikre at kun personell med gyldig opplæringsbevis utfører AC-service.",
      omfang: "Personbil og varebil under 3,5 t.",
      ansvar: ["Teknisk leder: sjekk gyldighet i kompetanse.", "Tekniker: ikke utfør uten bevis."],
      gjennomforing: [
        "Før AC-tømming/påfylling: bekreft gyldig personlig opplæringsbevis i kompetansemodulen.",
        "Sertifisering skjer ikke i HMS Nova. Registrer utløpsdato og last opp bevis.",
        "Håndter F-gass som farlig stoff. Unngå utslipp.",
      ],
      dokumentasjon: ["Opplæringsbevis med gyldighet.", "Servicehistorikk hos verksteddatasystem – ikke her."],
      avvikOppfolging: ["Service uten gyldig bevis er avvik."],
      revisjon: "Årlig.",
      kilder: ["Produktforskriften – F-gass"],
    },
  }),
  automotiveRoutine({
    title: "Personvern ved kundebil – nøkler, verdisaker og infotainment",
    description: "Når: i jobb. GDPR art. 5 og 6. Ikke bruk kundens data.",
    category: "PERSONVERN",
    legalReference: "GDPR art. 5 og 6",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Beskytte kundens eiendeler og personopplysninger i bil og systemer.",
      omfang: "Nøkler, vesker, tollbrikke, telefonkoblede systemer og verksteddata.",
      ansvar: ["Alle ansatte.", "Teknisk leder: nøkkelrutine."],
      gjennomforing: [
        "Nøkler i låst nøkkelskap. Verdisaker noteres og oppbevares. Ikke bruk kundens infotainment, kontakter eller apper privat.",
        "Personopplysninger i arbeidsordre behandles etter GDPR art. 5 og 6 – minimering og formålsbegrensning.",
        "Bilder av skade kun for jobben. Slett når formålet er oppfylt.",
      ],
      dokumentasjon: ["Nøkkelrutine.", "Eventuell skadelogg."],
      avvikOppfolging: ["Tapt nøkkel eller misbruk av kundedata er avvik/kundeklage.", "Varsle daglig leder."],
      revisjon: "Årlig.",
      kilder: ["GDPR art. 5 og 6", "Personopplysningsloven"],
    },
  }),
  automotiveRoutine({
    title: "PPE og åndedrettsvern på verkstedgulv",
    description: "Når: før jobb. FuA § 3-12, OLM kap. 15.",
    category: "BILVERKSTED",
    legalReference: "FuA § 3-12, OLM kap. 15",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Riktig verneutstyr etter jobbtype, inkludert tetthetstest av åndedrettsvern.",
      omfang: "Hele hallen, lakk og sveising.",
      ansvar: ["Arbeidsgiver: stiller utstyr og opplæring.", "Ansatt: bruker påbudt PPE."],
      gjennomforing: [
        "Vernesko, briller og hansker som standard. Hørselsvern i støysone. Åndedrettsvern ved sveising og kjemikalier.",
        "Ved lakk/diisocyanater: friskluft og vernetøy etter SDS. Sjekkliste PPE lakkering.",
        "Opplæring i bruk og vedlikehold (OLM kap. 15). Defekt utstyr kasseres.",
      ],
      dokumentasjon: ["PPE-utlevering.", "Opplæring åndedrettsvern."],
      avvikOppfolging: ["Arbeid uten påbudt PPE er avvik."],
      revisjon: "Årlig.",
      kilder: ["FuA § 3-12", "OLM kap. 15"],
    },
  }),
  automotiveRoutine({
    title: "Ergonomi, tunge løft og arbeid under bil",
    description: "Når: i jobb. AML § 4-4.",
    category: "BILVERKSTED",
    legalReference: "AML § 4-4",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Redusere muskel- og skjelettplager ved arbeid over hodet og tunge løft.",
      omfang: "Hjul, girkasse, motor og arbeid under hevet bil.",
      ansvar: ["Leder: hjelpemidler og rotasjon.", "Ansatt: be om hjelp ved tunge løft."],
      gjennomforing: [
        "Bruk løftebord, kran og tralle. To-manns løft når vekt eller stilling krever det.",
        "Varier arbeidsstilling. Pause ved langvarig arbeid over hodet.",
        "Kartlegg plagene i vernerunde og risikovurdering.",
      ],
      dokumentasjon: ["Risikovurdering ergonomi.", "Tilgjengelige hjelpemidler."],
      avvikOppfolging: ["Belastningsskade meldes som RUH/avvik."],
      revisjon: "Årlig.",
      kilder: ["AML § 4-4"],
    },
  }),
  automotiveRoutine({
    title: "Nyansatt og vikar – opplæring før selvstendig arbeid",
    description: "Når: før jobb. AML § 3-2. Billøfter og hallregler før alenearbeid.",
    category: "BILVERKSTED",
    legalReference: "AML § 3-2",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Ingen skal arbeide selvstendig før nødvendig opplæring er gitt.",
      omfang: "Nyansatte, vikarer og innleid.",
      ansvar: ["Leder: opplæringsplan.", "Fadder: gjennomgår hall, avvik og nødstans."],
      gjennomforing: [
        "Før første skift: rømning, avvik, PPE og hvem som er verneombud.",
        "Før selvstendig arbeid: billøfter-opplæring, kjemikalier og aktuelle SJA.",
        "Dokumenter i kompetansemodulen. Vikar får samme minimum som fast.",
      ],
      dokumentasjon: ["Opplæringsplan signert.", "Kompetansekort."],
      avvikOppfolging: ["Selvstendig arbeid uten opplæring er avvik."],
      revisjon: "Årlig.",
      kilder: ["AML § 3-2", "IK-HMS § 5 nr. 2"],
    },
  }),
  automotiveRoutine({
    title: "Trykkluft og kompressor",
    description: "Når: uke. FuA kap. 12 – kontroll av trykkluftanlegg.",
    category: "BILVERKSTED",
    legalReference: "FuA kap. 12",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Unngå slangebrudd, støy og feil bruk av trykkluft mot kropp.",
      omfang: "Kompressor, slanger og luftverktøy.",
      ansvar: ["Teknisk leder: periodisk kontroll.", "Bruker: visuell sjekk av slange."],
      gjennomforing: [
        "Aldri blås trykkluft mot hud eller klær. Ikke tørrblås bremsebelegg.",
        "Sjekk slanger og koblinger. Steng og avlast trykk før vedlikehold.",
        "Støy: hørselsvern ved kompressor. Periodisk kontroll etter produsent (FuA kap. 12).",
      ],
      dokumentasjon: ["Kontroll/kalibrering.", "Vedlikeholdslogg i dokumentarkiv."],
      avvikOppfolging: ["Slangebrudd eller misbruk er avvik."],
      revisjon: "Årlig.",
      kilder: ["FuA kap. 12"],
    },
  }),
  automotiveRoutine({
    title: "Gassflasker og batterilading",
    description: "Når: uke. Hydrogengass ved lading, ventilasjon. DSB farlig stoff.",
    category: "BILVERKSTED",
    legalReference: "Forskrift om håndtering av farlig stoff",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Trygg lagring av gassflasker og ventilasjon ved lading av blybatterier.",
      omfang: "Sveise- og kullsyreflasker, startbatterilading.",
      ansvar: ["Teknisk leder: lagring og kjetting.", "Bruker: steng flasker etter bruk."],
      gjennomforing: [
        "Flasker står oppreist, sikret og adskilt (full/tom, brennbart/oksygen). Ingen varme.",
        "Lading av blybatteri gir hydrogengass – ventiler, ingen gnist, ikke røyk.",
        "Følg DSB farlig stoff. Mengde over terskel kan utløse samtykke – vurder ved lagerendring.",
      ],
      dokumentasjon: ["Lagerkart.", "Eventuelt DSB-dokumentasjon."],
      avvikOppfolging: ["Løse flasker eller lading i tett rom er avvik."],
      revisjon: "Årlig.",
      kilder: ["Forskrift om håndtering av farlig stoff FOR-2009-06-08-602"],
    },
  }),
  automotiveRoutine({
    title: "Åpning, stenging og orden i hall",
    description: "Når: før jobb / uke. Rømningsvei, søl og nøkler.",
    category: "BILVERKSTED",
    legalReference: "Forskrift om brannforebygging, AML § 4-1",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Starte og avslutte dagen uten blokkerte rømningsveier, søl eller åpne nøkler.",
      omfang: "Hele verkstedet.",
      ansvar: ["Den som åpner/stenger.", "Alle: rydd egen plass."],
      gjennomforing: [
        "Åpning: sjekk rømning, slokkeutstyr, løftere og at avsug er klart.",
        "I løpet av dagen: tørk søl, hold gulv og porter frie.",
        "Stenging: nøkler i skap, kundebiler låst, farlig avfall lokk på, alarmer på.",
      ],
      dokumentasjon: ["Kort sjekk ved avvik.", "Nøkkelrutine."],
      avvikOppfolging: ["Blokkert rømning er umiddelbart avvik."],
      revisjon: "Årlig.",
      kilder: ["Forskrift om brannforebygging", "AML § 4-1"],
    },
  }),
];

const svvKvalitet: RoutineTemplateLibraryEntry[] = [
  automotiveRoutine({
    title: "Kvalitetsstyring etter verkstedforskriften §§ 15–17",
    description: "Når: år. PDCA, teknisk leders tilsyn. Statens vegvesen – ikke HMS-tilsyn.",
    category: "KVALITET_SVV",
    legalReference: "Verkstedforskriften §§ 15–17",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Dokumentere kvalitetsstyring slik at reparasjoner gir trafikksikre kjøretøy og godkjenningen opprettholdes.",
      omfang: "Alle godkjente verksted etter verkstedforskriften. Gjelder ikke PKK-rapportering til Vegvesenet.",
      ansvar: [
        "Daglig leder: ressurser og at systemet brukes.",
        "Teknisk leder: fører tilsyn med at praksis følger systemet (§ 16).",
        "Stedfortreder: trer inn etter §§ 10–11.",
      ],
      gjennomforing: [
        "Systemet dekker § 16 a–f: organisering, kompetanse, arbeidsprosedyre, kvalitetskontroll, kalibrering og avvik.",
        "Teknisk leder gjennomgår stikkprøver og avvik jevnlig. Årshjulet «Hold verkstedet godkjent» dekker AT og SVV.",
        "Systemet skal være ajour og tilgjengelig for ansatte og SVV (§ 17). Digital håndbok og versjonerte rutiner dekker dette.",
      ],
      dokumentasjon: ["Håndbok kapittel kvalitetsstyring.", "Roller i boarding/kompetanse.", "Årlig gjennomgang."],
      avvikOppfolging: ["Vesentlige eller gjentatte avvik kan gi tilbakekall av godkjenning (§ 19). Følg opp i avviksmodulen."],
      revisjon: "Minst årlig, og etter SVV-tilsyn.",
      kilder: [
        "Verkstedforskriften FOR-2020-10-28-2170 §§ 15–17 og § 19",
        "SVV veileder om kvalitetsstyring (17.02.2022)",
        "ISO 9001:2015 kap. 10.2",
      ],
    },
  }),
  automotiveRoutine({
    title: "Gjennomføring av reparasjonsarbeid",
    description: "Når: i jobb. Kunde → arbeidsordre → feilsøk → kontroll → utlevering. § 16 c. Ikke arbeidsordre-system.",
    category: "KVALITET_SVV",
    legalReference: "Verkstedforskriften § 16 c",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Én overordnet arbeidsprosedyre for hvordan verkstedet utfører reparasjon – ikke én prosedyre per jobbtype.",
      omfang: "Alle reparasjoner verkstedet er godkjent for. Produsentanvisning gjelder for detaljer.",
      ansvar: ["Teknisk leder: at prosedyren følges.", "Mekaniker: egenkontroll.", "Kundemottak: avklare oppdrag."],
      gjennomforing: [
        "Kundemottak: avklar oppdrag, nøkler og verdisaker. Opprett arbeidsordre i verkstedets fagsystem (ikke i HMS Nova).",
        "Feilsøk og reparasjon etter produsentanvisning. SJA/sjekkliste før høyrisiko (løft, høyvolt, sveising).",
        "Egenkontroll. Utlevering med forklaring til kunde. Samarbeidsavtaler for innleid kompetanse arkiveres som dokument.",
      ],
      dokumentasjon: ["Aktiv rutine med dato/godkjent/revidert.", "Samarbeidsavtaler.", "Kompetanse per rolle."],
      avvikOppfolging: ["Mangelfull kontroll eller feil reparasjon er kvalitetsavvik og kan være kundeklage."],
      revisjon: "Årlig eller ved endret godkjenning.",
      kilder: ["Verkstedforskriften § 16 c", "ISO 9001 kap. 8.5"],
    },
  }),
  automotiveRoutine({
    title: "Stikkprøve og kvalitetskontroll",
    description: "Når: uke. Egenkontroll hos mekaniker og stikkprøve av teknisk leder. § 16 d. Innleid kontroll for énmannsverksted.",
    category: "KVALITET_SVV",
    legalReference: "Verkstedforskriften § 16 d",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Kontrollere at utført arbeid er i samsvar med produsent og godkjenning.",
      omfang: "Alle ferdigstilte jobber (egenkontroll) og et utvalg stikkprøver av teknisk leder.",
      ansvar: ["Mekaniker: egenkontroll før utlevering.", "Teknisk leder: stikkprøver. Énmannsverksted: kjøpt/innleid kontroll."],
      gjennomforing: [
        "Mekaniker fyller sjekkliste egenkontroll jobb før bilen utleveres.",
        "Teknisk leder tar stikkprøver tilpasset størrelse og erfaring. Bruk sjekkliste «stikkprøve teknisk leder».",
        "Énmannsverksted skal ha avtale med annet verksted eller innleid kvalitetskontroll. Avtalen arkiveres.",
      ],
      dokumentasjon: ["Utfylte sjekklister.", "Avtale innleid kontroll."],
      avvikOppfolging: ["Funnet feil er kvalitetsavvik. Gjentatte feil utløser opplæring."],
      revisjon: "Årlig, hyppighet av stikkprøver vurderes da.",
      kilder: ["Verkstedforskriften § 16 d"],
    },
  }),
  automotiveRoutine({
    title: "Kalibrering og vedlikehold av godkjenningspliktig utstyr",
    description: "Når: år. § 16 e og § 7. Skjema med gyldig til-dato. Utstyrsregister med varsel er fase 2.",
    category: "KVALITET_SVV",
    legalReference: "Verkstedforskriften § 16 e og § 7",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Sikre at løftere, bremseprøver og annet godkjenningspliktig utstyr er kalibrert og vedlikeholdt.",
      omfang: "Utstyr verkstedet er godkjent for, inkludert løfter/grav og bremseprøver (kat. 02/03).",
      ansvar: ["Teknisk leder: frister og attester.", "HMS-ansvarlig: laste opp bevis i dokumentarkiv."],
      gjennomforing: [
        "Før utstyr tas i bruk: sjekk at kalibrering er gyldig. Bruk skjema med utstyr, serie, sist kalibrert, gyldig til og vedlegg attest.",
        "Utløpt kalibrering: stans bruk og opprett avvik. PKK-måleinstrumenter kalibreres av ISO/IEC 17025-organ der det kreves.",
        "Ikke bygg parallelt utstyrsregister i denne versjonen – attester ligger i dokumentarkiv.",
      ],
      dokumentasjon: ["Kalibreringsbevis.", "Skjema gyldig til."],
      avvikOppfolging: ["Utløpt kalibrering er avvik. SVV kan tilbakekalle godkjenning ved manglende registreringer."],
      revisjon: "Årlig og ved nytt utstyr.",
      kilder: ["Verkstedforskriften § 16 e og § 7", "FuA kap. 12"],
    },
  }),
  automotiveRoutine({
    title: "Avvik, kundeklage og SVV-pålegg",
    description: "Når: i jobb. § 16 f. Utfyller felles avviksmal med kundeklage og tilsyn. Type CUSTOMER/KVALITET.",
    category: "KVALITET_SVV",
    legalReference: "Verkstedforskriften § 16 f, ISO 9001 kap. 10.2",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Fange avvik fra internkontroll, kundeklager og tilsyn – ikke bare HMS-hendelser.",
      omfang: "HMS-avvik, kvalitetsavvik, kundeklager og pålegg fra Arbeidstilsynet eller Statens vegvesen.",
      ansvar: ["Alle kan melde.", "Teknisk leder: kvalitetsavvik og SVV.", "HMS-ansvarlig: AT-pålegg."],
      gjennomforing: [
        "Bruk avviksmodulen. Velg type KVALITET eller CUSTOMER ved kundeklage og reparasjonsfeil.",
        "SVV-pålegg og AT-pålegg registreres med frist og tiltak. Årsak, tiltak og effekt (ISO 9001 kap. 10.2).",
        "Felles avviksrutine (industryScope all) gjelder fortsatt for RUH og varsling. Denne utfyller med SVV/kunde.",
      ],
      dokumentasjon: ["Avvikssaker.", "Tilsynsrapporter."],
      avvikOppfolging: ["Gjentatte kundeklager på samme feil utløser gjennomgang av arbeidsprosedyre."],
      revisjon: "Årlig.",
      kilder: ["Verkstedforskriften § 16 f", "ISO 9001:2015 kap. 10.2", "IK-HMS § 5"],
    },
  }),
  automotiveRoutine({
    title: "Melding til Statens vegvesen ved endring som påvirker godkjenning",
    description: "Når: ved endring. Verkstedforskriften § 14. Meldingen skjer på vegvesen.no – vi lagrer ikke søknaden.",
    category: "KVALITET_SVV",
    legalReference: "Verkstedforskriften § 14",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Sikre at godkjenningen er ajour når lokaler, utstyr, ledelse eller tjenester endres.",
      omfang: "Endring av teknisk leder, stedfortreder, lokaler, utstyr eller godkjenningsomfang.",
      ansvar: ["Daglig leder / teknisk leder."],
      gjennomforing: [
        "Ved endring som påvirker godkjenning: meld fra til Statens vegvesen på vegvesen.no / Din side. HMS Nova sender ikke meldingen.",
        "Oppdater roller og kompetanse her samtidig.",
        "Arkiver kvittering som dokument.",
      ],
      dokumentasjon: ["Kvittering fra Vegvesenet.", "Oppdaterte roller."],
      avvikOppfolging: ["Manglende melding er avvik og kan ramme godkjenningen."],
      revisjon: "Ved organisasjonsendring.",
      kilder: ["Verkstedforskriften § 14", "https://www.vegvesen.no/kjoretoy/eie-og-vedlikeholde/for-verkstedbransjen/"],
    },
  }),
  automotiveRoutine({
    title: "Omfattende skadereparasjon – intern prosedyre mot vegvesen.no",
    description: "Når: i jobb. Pek til innrapportering på vegvesen.no. Vi bygger ikke skaderegister.",
    category: "KVALITET_SVV",
    legalReference: "Verkstedforskriften, SVV skaderapport",
    industryScope: AUTOMOTIVE,
    content: {
      formaal: "Sikre at omfattende skadereparasjon rapporteres der loven krever det, uten å duplisere Vegvesenets system.",
      omfang: "Skadeverksted 02 m.fl. der målebrev og egenerklæring skal inn før bilen tas i bruk.",
      ansvar: ["Teknisk leder: at rapportering skjer.", "Mekaniker: produsentanvisning."],
      gjennomforing: [
        "Følg produsentanvisning for retning, måling og sveis.",
        "Innrapportering av skaderapport (målebrev, 4-hjulsmåling, bilder, egenerklæring) skjer på vegvesen.no. HMS Nova tar ikke imot opplasting.",
        "Lenke: https://www.vegvesen.no/kjoretoy/eie-og-vedlikeholde/for-verkstedbransjen/for-verksteder/godkjente-verksteder/meld-inn-skaderapport/",
      ],
      dokumentasjon: ["Intern sjekk at melding er sendt (notat/avvik hvis glemt)."],
      avvikOppfolging: ["Utlevering uten påkrevd melding er kvalitetsavvik."],
      revisjon: "Årlig.",
      kilder: ["SVV: meld inn skaderapport", "Produsentanvisning"],
    },
  }),
];

const valgfrie: RoutineTemplateLibraryEntry[] = [
  automotiveRoutine({
    title: "Sprøytelakkering og diisocyanater",
    description: "Når: før jobb. Underkategori skade/lakk. FuA § 3-12 og REACH.",
    category: "BILVERKSTED",
    legalReference: "FuA § 3-12, REACH",
    industryScope: LAKK,
    content: {
      formaal: "Forebygge astma og eksponering for diisocyanater og løsemidler ved lakkering.",
      omfang: "Sprøyting, blanding og sliping i lakkavdeling.",
      ansvar: ["Lakkansvarlig: opplæring og friskluft.", "HMS: stoffkartotek-scan for isocyanater."],
      gjennomforing: [
        "Ingen sprøyting uten gyldig diisocyanat-opplæring og friskluft. Sjekkliste PPE lakkering.",
        "Sprøyteboks med avsug og forrigling. SJA «Lakkering i sprøyteboks».",
        "Eksponeringsregister 60 år for diisocyanater og løsemidler.",
      ],
      dokumentasjon: ["Opplæringsbevis.", "SDS.", "Eksponeringsregister."],
      avvikOppfolging: ["Sprøyting uten friskluft er stans og avvik."],
      revisjon: "Årlig.",
      kilder: ["FuA § 3-12", "REACH – diisocyanater ≥ 0,1 %"],
    },
  }),
  automotiveRoutine({
    title: "Brannfarlig stoff og ATEX i sprøyteboks",
    description: "Når: uke. Underkategori skade/lakk. DSB, ATEX-brukerforskrift, EN 16985.",
    category: "BILVERKSTED",
    legalReference: "ATEX-brukerforskrift, DSB farlig stoff, EN 16985",
    industryScope: LAKK,
    content: {
      formaal: "Dokumentere eksplosjonsvern i sprøyteboks og trygg lagring av løsemidler.",
      omfang: "Sprøyteboks og lakk-/tynnerlager.",
      ansvar: ["Teknisk leder: ATEX-dokument.", "Lakkansvarlig: orden og EX-utstyr."],
      gjennomforing: [
        "Ha eksplosjonsverndokument. Sone 2 i boks etter EN 16985. Forrigling av ventilasjon.",
        "Kun EX-godkjent utstyr i sonen. Ingen gnist, åpen ild eller ladende telefon.",
        "Løsemidler i brannskap etter DSB farlig stoff. Mengde i daglig bruk holdes lav.",
      ],
      dokumentasjon: ["ATEX-brukerdokument.", "Lagerkart farlig stoff."],
      avvikOppfolging: ["Boks i bruk uten avsug/forrigling er stans."],
      revisjon: "Årlig.",
      kilder: ["ATEX-brukerforskrift FOR-2003-06-10-727", "EN 16985", "FOR-2009-06-08-602"],
    },
  }),
  automotiveRoutine({
    title: "Slipestøv og karosseriarbeid",
    description: "Når: i jobb. Underkategori skade/lakk.",
    category: "BILVERKSTED",
    legalReference: "AML § 4-5, arbeidsplassforskriften § 7-1",
    industryScope: LAKK,
    content: {
      formaal: "Redusere innånding av slipestøv og støy ved karosseriarbeid.",
      omfang: "Sletting, kapping og retting.",
      ansvar: ["Karosseriansvarlig.", "Ansatt: avsug og PPE."],
      gjennomforing: [
        "Bruk punktavsug/slipemaskin med utsug. Åndedrettsvern etter SDS for sparkel/lakk.",
        "Hørselsvern. Rydd støv med støvsuger, ikke tørrfeiing.",
        "Sveising på karosseri følger sveiserutinen.",
      ],
      dokumentasjon: ["Vernerunde.", "PPE."],
      avvikOppfolging: ["Sletting uten avsug i lukket rom er avvik."],
      revisjon: "Årlig.",
      kilder: ["AML § 4-5", "Arbeidsplassforskriften § 7-1"],
    },
  }),
  automotiveRoutine({
    title: "Understellsbehandling",
    description: "Når: i jobb. Underkategori skade/lakk. Løsemidler og sprøytetåke.",
    category: "BILVERKSTED",
    legalReference: "AML § 4-5, FuA kap. 3",
    industryScope: LAKK,
    content: {
      formaal: "Trygg påføring av understellsmasse og rustbehandling.",
      omfang: "Sprøyting og stryking av understellsprodukter.",
      ansvar: ["Utførende: SDS og avsug.", "HMS: stoffkartotek."],
      gjennomforing: [
        "Les SDS. Bruk avsug og åndedrettsvern. Unngå hudkontakt.",
        "Ikke sprøyt nær åpen ild eller sveis. Avfall som farlig avfall.",
        "Hevet bil etter løfterutinen.",
      ],
      dokumentasjon: ["SDS.", "PPE."],
      avvikOppfolging: ["Sprøyting uten vern er avvik."],
      revisjon: "Årlig.",
      kilder: ["AML § 4-5", "FuA kap. 3"],
    },
  }),
  automotiveRoutine({
    title: "Habilitet ved EU-kontroll",
    description: "Når: før jobb. Underkategori PKK. PKK-forskriften § 12c / § 14 f. Ikke full habilitetsmotor.",
    category: "KVALITET_SVV",
    legalReference: "PKK-forskriften § 12c og § 14 f",
    industryScope: PKK,
    content: {
      formaal: "Sikre personlig og systemhabilitet slik at kontrollen er uavhengig.",
      omfang: "Kontrollorgan / EU-kontroll. Egne biler og biler verkstedet har reparert.",
      ansvar: ["Teknisk leder kontrollorgan.", "Kontrollør: erklær inhabilitet."],
      gjennomforing: [
        "Kontrollør skal ikke kontrollere kjøretøy der habiliteten er svekket (egen bil, nærstående, eller jobb de selv har utført – etter PKK-reglene).",
        "Systemhabilitet: skille mellom verkstedjobb og kontroll. Dokumenter hvem som kontrollerer.",
        "Praktisk kontrollrekkefølge «slik gjør vi det i vårt lokale» beskrives i eget dokument. Resultat meldes på vegvesen.no – ikke i HMS Nova.",
      ],
      dokumentasjon: ["Habilitetsnotat ved tvil.", "Kompetanse kontrollør."],
      avvikOppfolging: ["Inhabil kontroll er alvorlig kvalitetsavvik."],
      revisjon: "Årlig.",
      kilder: ["PKK-forskriften §§ 12c, 13–15", "https://www.vegvesen.no/kjoretoy/eie-og-vedlikeholde/for-verkstedbransjen/for-kontrollorgan/"],
    },
  }),
];

export const AUTOMOTIVE_ROUTINE_TEMPLATES: RoutineTemplateLibraryEntry[] = [
  ...kjerne,
  ...svvKvalitet,
  ...valgfrie,
];
