import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  BarChart3,
  Beaker,
  BookOpen,
  Building2,
  Calendar,
  ClipboardCheck,
  Clock,
  FileBarChart,
  FileCheck2,
  FileText,
  Flame,
  FlaskConical,
  FolderArchive,
  FolderOpen,
  Gauge,
  GraduationCap,
  HardHat,
  Headphones,
  HeartPulse,
  Layers,
  LayoutDashboard,
  Leaf,
  LifeBuoy,
  ListChecks,
  ListTodo,
  Lock,
  Mail,
  MessageSquare,
  Monitor,
  Moon,
  PersonStanding,
  Scale,
  Settings,
  Shield,
  ShieldCheck,
  Target,
  ThumbsUp,
  Truck,
  UserPlus,
  Users,
  UtensilsCrossed,
  Wine,
} from "lucide-react";

export const DASHBOARD_NAV_ICONS: Record<string, LucideIcon> = {
  "/dashboard": LayoutDashboard,
  "/dashboard/meldinger": Mail,
  "/dashboard/hms-handbok": BookOpen,
  "/dashboard/documents": FileText,
  "/dashboard/rutiner": ListChecks,
  "/dashboard/samsvarserklaringer": FileCheck2,
  "/dashboard/juridisk-register": Scale,
  "/dashboard/incidents": AlertCircle,
  "/dashboard/projects": FolderOpen,
  "/dashboard/construction-compliance": HardHat,
  "/dashboard/hms-tavle": Monitor,
  "/dashboard/incidents/statistics": BarChart3,
  "/dashboard/sja": HardHat,
  "/dashboard/inspections": ShieldCheck,
  "/dashboard/fire-drills": Flame,
  "/dashboard/training": GraduationCap,
  "/dashboard/actions": ListTodo,
  "/dashboard/chemicals": Beaker,
  "/dashboard/exposure-register": FlaskConical,
  "/dashboard/ik-mat": UtensilsCrossed,
  "/dashboard/skjenking": Wine,
  "/dashboard/beredskap": LifeBuoy,
  "/dashboard/aktivitetssikkerhet": PersonStanding,
  "/dashboard/transport": Truck,
  "/dashboard/bht-nattarbeid": Moon,
  "/dashboard/risks": AlertTriangle,
  "/dashboard/risk-register": Layers,
  "/dashboard/wellbeing": HeartPulse,
  "/dashboard/complaints": MessageSquare,
  "/dashboard/feedback": ThumbsUp,
  "/dashboard/environment": Leaf,
  "/dashboard/bcm": LifeBuoy,
  "/dashboard/audits": ClipboardCheck,
  "/dashboard/management-reviews": FileBarChart,
  "/dashboard/annual-hms-plan": ListChecks,
  "/dashboard/meetings": Calendar,
  "/dashboard/time-registration": Clock,
  "/dashboard/fravaer": Calendar,
  "/dashboard/onboarding": UserPlus,
  "/dashboard/personalarkiv": FolderArchive,
  "/dashboard/medarbeidersamtale": MessageSquare,
  "/dashboard/whistleblowing": Shield,
  "/konfidensielt": Lock,
  "/dashboard/goals": Target,
  "/dashboard/hms-cockpit": Gauge,
  "/dashboard/benchmark": BarChart3,
  "/dashboard/brukere": Users,
  "/dashboard/organisasjonskart": Building2,
  "/dashboard/aktivitetslogg": Activity,
  "/dashboard/support": Headphones,
  "/dashboard/settings": Settings,
};
