import {
  AlertTriangle,
  FileText,
  ShieldAlert,
  ClipboardCheck,
  GraduationCap,
  CheckSquare,
  Beaker,
  Flame,
  Droplets,
  Zap,
  Building2,
  UtensilsCrossed,
  Stethoscope,
  SprayCan,
  CalendarDays,
  BookOpen,
  HardHat,
  FileWarning,
  Heart,
  Leaf,
  ShieldCheck,
  Search,
  Users,
  Target,
  MessageSquareWarning,
  MessageSquare,
  ScrollText,
  type LucideIcon,
  BarChart3,
  ListTodo,
  Sparkles,
  Activity,
  Clock,
  Siren,
} from "lucide-react";

export interface WidgetDefinition {
  id: string;
  label: string;
  description: string;
  icon: LucideIcon;
  href: string;
  category: WidgetCategory;
  color: string;
  bgColor: string;
  borderColor: string;
  permission?: string;
  isAdvanced?: boolean;
}

export type WidgetCategory =
  | "hms"
  | "sikkerhet"
  | "helse"
  | "dokumenter"
  | "personal"
  | "kvalitet"
  | "spesial";

export const WIDGET_CATEGORIES: Record<WidgetCategory, { label: string; color: string }> = {
  hms: { label: "HMS Kjerne", color: "text-blue-700" },
  sikkerhet: { label: "Sikkerhet & Beredskap", color: "text-red-700" },
  helse: { label: "Helse & Miljø", color: "text-emerald-700" },
  dokumenter: { label: "Dokumenter & Rutiner", color: "text-slate-700" },
  personal: { label: "Personal & Administrasjon", color: "text-amber-700" },
  kvalitet: { label: "Kvalitet & Forbedring", color: "text-indigo-700" },
  spesial: { label: "Dashboard-widgeter", color: "text-purple-700" },
};

export const WIDGET_REGISTRY: WidgetDefinition[] = [
  // HMS Kjerne
  {
    id: "incidents",
    label: "Avvik",
    description: "Hendelser, avvik og uønskede hendelser (AML § 5-2)",
    icon: AlertTriangle,
    href: "/dashboard/incidents",
    category: "hms",
    color: "text-orange-700",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    permission: "incidents",
  },
  {
    id: "risks",
    label: "Risiko­kartlegging",
    description: "Risikovurderinger og risikomatrise",
    icon: ShieldAlert,
    href: "/dashboard/risks",
    category: "hms",
    color: "text-red-700",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    permission: "risks",
    isAdvanced: true,
  },
  {
    id: "actions",
    label: "Tiltak",
    description: "Korrigerende og forebyggende tiltak",
    icon: CheckSquare,
    href: "/dashboard/actions",
    category: "hms",
    color: "text-blue-700",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
    permission: "actions",
  },
  {
    id: "inspections",
    label: "Vernerunde",
    description: "Vernerunder og inspeksjoner",
    icon: ClipboardCheck,
    href: "/dashboard/inspections",
    category: "hms",
    color: "text-teal-700",
    bgColor: "bg-teal-50",
    borderColor: "border-teal-200",
    permission: "inspections",
  },
  {
    id: "sja",
    label: "SJA",
    description: "Sikker Jobb Analyse",
    icon: HardHat,
    href: "/dashboard/sja",
    category: "hms",
    color: "text-yellow-700",
    bgColor: "bg-yellow-50",
    borderColor: "border-yellow-200",
    permission: "sja",
  },
  {
    id: "ruh",
    label: "RUH",
    description: "Rapport uønsket hendelse",
    icon: FileWarning,
    href: "/dashboard/ruh",
    category: "hms",
    color: "text-amber-700",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
    permission: "ruh",
  },
  {
    id: "training",
    label: "Opplæring",
    description: "Opplæring og kompetanse for ansatte",
    icon: GraduationCap,
    href: "/dashboard/training",
    category: "hms",
    color: "text-purple-700",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
    permission: "training",
  },

  // Sikkerhet & Beredskap
  {
    id: "fire-safety",
    label: "Brann",
    description: "Brannsikkerhet, rømningsplaner og brannøvelser",
    icon: Flame,
    href: "/dashboard/forms?q=brann",
    category: "sikkerhet",
    color: "text-red-600",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
  },
  {
    id: "electrical",
    label: "Samsvarserklæringer",
    description: "Elektro, rørlegger, ventilasjon og andre fag",
    icon: Zap,
    href: "/dashboard/samsvarserklaringer",
    category: "sikkerhet",
    color: "text-yellow-600",
    bgColor: "bg-yellow-50",
    borderColor: "border-yellow-200",
  },
  {
    id: "water-safety",
    label: "Vann",
    description: "Vannsikkerhet og legionella-kontroll",
    icon: Droplets,
    href: "/dashboard/forms?q=vann",
    category: "sikkerhet",
    color: "text-cyan-600",
    bgColor: "bg-cyan-50",
    borderColor: "border-cyan-200",
  },
  {
    id: "elevator",
    label: "Heis",
    description: "Heiskontroll og vedlikehold",
    icon: Building2,
    href: "/dashboard/forms?q=heis",
    category: "sikkerhet",
    color: "text-slate-600",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
  },
  {
    id: "bcm",
    label: "Beredskap",
    description: "Beredskapsplaner og krisehåndtering (BCM)",
    icon: ShieldCheck,
    href: "/dashboard/bcm",
    category: "sikkerhet",
    color: "text-rose-700",
    bgColor: "bg-rose-50",
    borderColor: "border-rose-200",
    permission: "bcm",
    isAdvanced: true,
  },

  // Helse & Miljø
  {
    id: "chemicals",
    label: "Kjemikalier",
    description: "Stoffkartotek og kjemikaliehåndtering",
    icon: Beaker,
    href: "/dashboard/chemicals",
    category: "helse",
    color: "text-emerald-700",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    permission: "chemicals",
  },
  {
    id: "medicine",
    label: "Medisin",
    description: "Medisinhåndtering og oversikt",
    icon: Stethoscope,
    href: "/dashboard/forms?q=medisin",
    category: "helse",
    color: "text-pink-600",
    bgColor: "bg-pink-50",
    borderColor: "border-pink-200",
  },
  {
    id: "medical-equipment",
    label: "Medisinsk utstyr",
    description: "Oversikt over medisinsk utstyr og vedlikehold",
    icon: Siren,
    href: "/dashboard/forms?q=medisinsk%20utstyr",
    category: "helse",
    color: "text-rose-600",
    bgColor: "bg-rose-50",
    borderColor: "border-rose-200",
  },
  {
    id: "cleaning",
    label: "Renhold",
    description: "Renholdskontroll og hygiene",
    icon: SprayCan,
    href: "/dashboard/forms?q=renhold",
    category: "helse",
    color: "text-sky-600",
    bgColor: "bg-sky-50",
    borderColor: "border-sky-200",
  },
  {
    id: "food-safety",
    label: "Mat",
    description: "Matsikkerhet og hygienekontroll",
    icon: UtensilsCrossed,
    href: "/dashboard/forms?q=mat",
    category: "helse",
    color: "text-green-600",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
  },
  {
    id: "wellbeing",
    label: "Arbeidsmiljø",
    description: "Psykososialt arbeidsmiljø og trivsel",
    icon: Heart,
    href: "/dashboard/wellbeing",
    category: "helse",
    color: "text-pink-700",
    bgColor: "bg-pink-50",
    borderColor: "border-pink-200",
    permission: "wellbeing",
  },
  {
    id: "environment",
    label: "Miljø",
    description: "Miljøstyring og ytre miljø (ISO 14001)",
    icon: Leaf,
    href: "/dashboard/environment",
    category: "helse",
    color: "text-green-700",
    bgColor: "bg-green-50",
    borderColor: "border-green-200",
    permission: "environment",
    isAdvanced: true,
  },

  // Dokumenter & Rutiner
  {
    id: "documents",
    label: "Dokumenter",
    description: "Dokumentstyring og versjonsadministrasjon",
    icon: FileText,
    href: "/dashboard/documents",
    category: "dokumenter",
    color: "text-slate-700",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
    permission: "documents",
  },
  {
    id: "routines",
    label: "Rutiner og instrukser",
    description: "Bedriftens rutiner, instrukser og prosedyrer",
    icon: BookOpen,
    href: "/dashboard/rutiner",
    category: "dokumenter",
    color: "text-indigo-600",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
  },
  {
    id: "forms",
    label: "Skjemaer",
    description: "Digitale skjemaer og sjekklister",
    icon: ScrollText,
    href: "/dashboard/forms",
    category: "dokumenter",
    color: "text-violet-600",
    bgColor: "bg-violet-50",
    borderColor: "border-violet-200",
    permission: "forms",
    isAdvanced: true,
  },

  // Personal & Administrasjon
  {
    id: "absence",
    label: "Ferie/Fravær",
    description: "Fravær, ferie og permisjoner",
    icon: CalendarDays,
    href: "/dashboard/time-registration",
    category: "personal",
    color: "text-amber-600",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
  },
  {
    id: "organization",
    label: "Organisasjon",
    description: "Organisasjonsstruktur og ansatte",
    icon: Users,
    href: "/dashboard/settings",
    category: "personal",
    color: "text-blue-600",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
  },
  {
    id: "meetings",
    label: "Møter",
    description: "AMU-møter, verneombudsmøter og referat",
    icon: CalendarDays,
    href: "/dashboard/meetings",
    category: "personal",
    color: "text-indigo-600",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
    permission: "meetings",
    isAdvanced: true,
  },

  // Kvalitet & Forbedring
  {
    id: "audits",
    label: "Revisjoner",
    description: "Interne og eksterne revisjoner",
    icon: Search,
    href: "/dashboard/audits",
    category: "kvalitet",
    color: "text-indigo-700",
    bgColor: "bg-indigo-50",
    borderColor: "border-indigo-200",
    permission: "audits",
    isAdvanced: true,
  },
  {
    id: "goals",
    label: "Mål",
    description: "HMS-mål og KPI-oppfølging",
    icon: Target,
    href: "/dashboard/goals",
    category: "kvalitet",
    color: "text-emerald-700",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
    permission: "goals",
    isAdvanced: true,
  },
  {
    id: "complaints",
    label: "Klager",
    description: "Kundeklager og reklamasjoner",
    icon: MessageSquareWarning,
    href: "/dashboard/complaints",
    category: "kvalitet",
    color: "text-orange-600",
    bgColor: "bg-orange-50",
    borderColor: "border-orange-200",
    permission: "complaints",
    isAdvanced: true,
  },
  {
    id: "feedback",
    label: "Tilbake­meldinger",
    description: "Kundetilbakemeldinger og forbedringsforslag",
    icon: MessageSquare,
    href: "/dashboard/feedback",
    category: "kvalitet",
    color: "text-sky-600",
    bgColor: "bg-sky-50",
    borderColor: "border-sky-200",
    permission: "feedback",
    isAdvanced: true,
  },
  {
    id: "risk-register",
    label: "Risiko­register",
    description: "Samlet risikooversikt for virksomheten",
    icon: ScrollText,
    href: "/dashboard/risk-register",
    category: "kvalitet",
    color: "text-red-600",
    bgColor: "bg-red-50",
    borderColor: "border-red-200",
    permission: "riskRegister",
    isAdvanced: true,
  },

  // Spesial-widgeter (dashboard-spesifikke)
  {
    id: "widget-task-center",
    label: "Oppgavesenter",
    description: "Varsling for oppgaver som trenger oppfølging",
    icon: ListTodo,
    href: "/dashboard/actions",
    category: "spesial",
    color: "text-blue-700",
    bgColor: "bg-blue-50",
    borderColor: "border-blue-200",
  },
  {
    id: "widget-hms-score",
    label: "HMS-puls",
    description: "Overordnet HMS-status for tilsyn og revisjon",
    icon: BarChart3,
    href: "/dashboard/hms-pulse",
    category: "spesial",
    color: "text-emerald-700",
    bgColor: "bg-emerald-50",
    borderColor: "border-emerald-200",
  },
  {
    id: "widget-ai-assistant",
    label: "AI-assistent",
    description: "Varsler og anbefalinger",
    icon: Sparkles,
    href: "/dashboard/notifications",
    category: "spesial",
    color: "text-purple-700",
    bgColor: "bg-purple-50",
    borderColor: "border-purple-200",
  },
  {
    id: "widget-activity-feed",
    label: "Aktivitet",
    description: "Siste aktivitet som varsling",
    icon: Activity,
    href: "/dashboard/notifications",
    category: "spesial",
    color: "text-slate-700",
    bgColor: "bg-slate-50",
    borderColor: "border-slate-200",
  },
  {
    id: "widget-my-tasks",
    label: "Mine oppgaver",
    description: "Personlige oppgaver og frister",
    icon: Clock,
    href: "/dashboard/actions",
    category: "spesial",
    color: "text-amber-700",
    bgColor: "bg-amber-50",
    borderColor: "border-amber-200",
  },
];

export const DEFAULT_WIDGET_IDS = [
  "incidents",
  "fire-safety",
  "electrical",
  "medicine",
  "food-safety",
  "water-safety",
  "medical-equipment",
  "cleaning",
  "actions",
  "inspections",
  "documents",
  "routines",
  "widget-task-center",
  "widget-hms-score",
];

export const HEALTHCARE_DEFAULT_WIDGET_IDS = [
  "fire-safety",
  "medicine",
  "food-safety",
  "medical-equipment",
  "cleaning",
  "water-safety",
  "electrical",
  "actions",
  "incidents",
  "training",
  "documents",
  "widget-task-center",
  "widget-hms-score",
];

export function getDefaultWidgetIdsForIndustry(industry: string | null | undefined): string[] {
  const normalizedIndustry = (industry || "").trim().toLowerCase();

  if (normalizedIndustry === "healthcare") {
    return HEALTHCARE_DEFAULT_WIDGET_IDS;
  }

  return DEFAULT_WIDGET_IDS;
}

export function getWidgetById(id: string): WidgetDefinition | undefined {
  return WIDGET_REGISTRY.find((w) => w.id === id);
}
