-- Sykefraværsoppfølging: AML § 4-6, ftrl. § 8-7a

-- NotificationType: legge til nye verdier for oppfølging
ALTER TABLE `Notification`
  MODIFY `type` ENUM(
    'NEW_INCIDENT','INCIDENT_UPDATED','INCIDENT_CLOSED','INCIDENT_OVERDUE',
    'FORM_SUBMITTED','FORM_APPROVED','FORM_REJECTED',
    'WHISTLEBLOWING','WHISTLEBLOWING_MSG',
    'MEASURE_OVERDUE','MEASURE_ASSIGNED','MEASURE_DUE_SOON','MEASURE_REMINDER',
    'AUDIT_SCHEDULED','AUDIT_REMINDER','AUDIT_FINDING_OPEN',
    'TRAINING_DUE','TRAINING_EXPIRED','TRAINING_ASSIGNED',
    'MEETING_REMINDER','MEETING_SCHEDULED',
    'INSPECTION_REMINDER','INSPECTION_SCHEDULED','INSPECTION_OVERDUE','INSPECTION_FINDING',
    'RISK_REVIEW_DUE','RISK_HIGH_SCORE','RISK_CONTROL_DUE',
    'DOCUMENT_REVIEW_DUE','DOCUMENT_EXPIRED','DOCUMENT_APPROVED',
    'ROUTINE_ASSIGNED','ROUTINE_REVIEW_DUE',
    'CHEMICAL_SDS_REVIEW','CHEMICAL_EXPIRED',
    'GOAL_UPDATED','GOAL_COMPLETED','GOAL_OVERDUE',
    'EMPLOYEE_REVIEW_DUE','EMPLOYEE_REVIEW_UPCOMING','EMPLOYEE_REVIEW_SIGN',
    'DAILY_DIGEST','WEEKLY_DIGEST','SYSTEM_ALERT',
    'GUEST_SUBMISSION','SUPPORT_TICKET','SUPPORT_MSG',
    'IMPROVEMENT_SUGGESTION','IMPROVEMENT_REMINDER','HMS_SCORE_DROP','HMS_SCORE_MILESTONE',
    'ROUTINE_COMPLIANCE_ALERT','LAW_CHANGE_ALERT',
    'HANDBOOK_APPROVAL_REQUESTED','HANDBOOK_NEW_VERSION',
    'ABSENCE_REQUESTED','ABSENCE_APPROVED','ABSENCE_REJECTED',
    'SICK_LEAVE_PLAN_DUE','SICK_LEAVE_DIALOG_DUE','SICK_LEAVE_OVERDUE'
  ) NOT NULL;

-- SickLeaveFollowUp table
CREATE TABLE `SickLeaveFollowUp` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `absenceId` VARCHAR(191) NOT NULL,
  `milestone` ENUM('FOLLOW_UP_PLAN','DIALOG_MEETING_1','ACTIVITY_REQUIREMENT','DIALOG_MEETING_2','DIALOG_MEETING_3','MAX_DATE') NOT NULL,
  `status` ENUM('NOT_STARTED','IN_PROGRESS','COMPLETED','SKIPPED') NOT NULL DEFAULT 'NOT_STARTED',
  `dueDate` DATE NOT NULL,
  `completedAt` DATETIME(3) NULL,
  `completedById` VARCHAR(191) NULL,
  `skippedReason` VARCHAR(191) NULL,
  `notes` TEXT NULL,

  `workAssessment` TEXT NULL,
  `accommodations` TEXT NULL,
  `externalSupport` TEXT NULL,
  `planSentToDoctor` BOOLEAN NOT NULL DEFAULT false,
  `planSentAt` DATETIME(3) NULL,

  `meetingDate` DATETIME(3) NULL,
  `meetingNotes` TEXT NULL,
  `attendees` TEXT NULL,
  `doctorAttended` BOOLEAN NOT NULL DEFAULT false,
  `navAttended` BOOLEAN NOT NULL DEFAULT false,

  `attachmentUrl` VARCHAR(191) NULL,
  `attachmentName` VARCHAR(191) NULL,

  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `SickLeaveFollowUp_absenceId_milestone_key` ON `SickLeaveFollowUp`(`absenceId`, `milestone`);
CREATE INDEX `SickLeaveFollowUp_tenantId_status_idx` ON `SickLeaveFollowUp`(`tenantId`, `status`);
CREATE INDEX `SickLeaveFollowUp_tenantId_dueDate_idx` ON `SickLeaveFollowUp`(`tenantId`, `dueDate`);

ALTER TABLE `SickLeaveFollowUp` ADD CONSTRAINT `SickLeaveFollowUp_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `SickLeaveFollowUp` ADD CONSTRAINT `SickLeaveFollowUp_absenceId_fkey` FOREIGN KEY (`absenceId`) REFERENCES `Absence`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `SickLeaveFollowUp` ADD CONSTRAINT `SickLeaveFollowUp_completedById_fkey` FOREIGN KEY (`completedById`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
