-- Fravær-modul: AML § 5-1 (4), Ferieloven, GDPR art. 9

-- NotificationType: legge til nye verdier bakerst (MySQL ENUM in-place)
ALTER TABLE `Notification`
  MODIFY `type` ENUM(
    'NEW_INCIDENT','INCIDENT_UPDATED','INCIDENT_CLOSED','INCIDENT_OVERDUE',
    'FORM_SUBMITTED','FORM_APPROVED','FORM_REJECTED',
    'WHISTLEBLOWING','WHISTLEBLOWING_MSG',
    'MEASURE_OVERDUE','MEASURE_ASSIGNED','MEASURE_DUE_SOON','MEASURE_REMINDER',
    'AUDIT_SCHEDULED','AUDIT_REMINDER','AUDIT_FINDING_OPEN',
    'TRAINING_DUE','TRAINING_EXPIRED','TRAINING_ASSIGNED',
    'MEETING_REMINDER','MEETING_SCHEDULED',
    'INSPECTION_REMINDER','INSPECTION_SCHEDULED','INSPECTION_OVERDUE','INSPECTION_FINDING',
    'RISK_REVIEW_DUE','RISK_HIGH_SCORE','RISK_CONTROL_DUE',
    'DOCUMENT_REVIEW_DUE','DOCUMENT_EXPIRED','DOCUMENT_APPROVED',
    'ROUTINE_ASSIGNED','ROUTINE_REVIEW_DUE',
    'CHEMICAL_SDS_REVIEW','CHEMICAL_EXPIRED',
    'GOAL_UPDATED','GOAL_COMPLETED','GOAL_OVERDUE',
    'EMPLOYEE_REVIEW_DUE','EMPLOYEE_REVIEW_UPCOMING','EMPLOYEE_REVIEW_SIGN',
    'DAILY_DIGEST','WEEKLY_DIGEST','SYSTEM_ALERT',
    'GUEST_SUBMISSION','SUPPORT_TICKET','SUPPORT_MSG',
    'IMPROVEMENT_SUGGESTION','IMPROVEMENT_REMINDER','HMS_SCORE_DROP','HMS_SCORE_MILESTONE',
    'ROUTINE_COMPLIANCE_ALERT','LAW_CHANGE_ALERT',
    'HANDBOOK_APPROVAL_REQUESTED','HANDBOOK_NEW_VERSION',
    'ABSENCE_REQUESTED','ABSENCE_APPROVED','ABSENCE_REJECTED'
  ) NOT NULL;

-- Absence table
CREATE TABLE `Absence` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `type` ENUM('SELF_CERTIFIED','SICK_LEAVE','PARENTAL_LEAVE','VACATION','LEAVE_OF_ABSENCE','COMPENSATORY','CARE_DAYS','MILITARY','BEREAVEMENT','OTHER') NOT NULL,
  `status` ENUM('PENDING','APPROVED','REJECTED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `workdays` DOUBLE NULL,
  `percentage` INTEGER NOT NULL DEFAULT 100,
  `reason` TEXT NULL,
  `doctorName` VARCHAR(191) NULL,
  `diagnosisCode` VARCHAR(191) NULL,
  `selfCertifiedDays` INTEGER NULL,
  `approvedById` VARCHAR(191) NULL,
  `approvedAt` DATETIME(3) NULL,
  `rejectedById` VARCHAR(191) NULL,
  `rejectedAt` DATETIME(3) NULL,
  `rejectedReason` VARCHAR(191) NULL,
  `attachmentUrl` VARCHAR(191) NULL,
  `attachmentName` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE INDEX `Absence_tenantId_userId_idx` ON `Absence`(`tenantId`, `userId`);
CREATE INDEX `Absence_tenantId_startDate_idx` ON `Absence`(`tenantId`, `startDate`);
CREATE INDEX `Absence_tenantId_type_status_idx` ON `Absence`(`tenantId`, `type`, `status`);

ALTER TABLE `Absence` ADD CONSTRAINT `Absence_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `Absence` ADD CONSTRAINT `Absence_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `Absence` ADD CONSTRAINT `Absence_approvedById_fkey` FOREIGN KEY (`approvedById`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
